const product = {
    woman: [
        {
            id: 'woman01',
            name: 'COC 射手阿波罗99%真实肉感伸缩摇摆阳具 20cm[货号:QZ1714]',
            images: [
                require('./woman/01/01.jpg'),
                require('./woman/01/02.jpg'),
                require('./woman/01/03.jpg'),
                require('./woman/01/04.jpg'),
                require('./woman/01/05.jpg'),
                require('./woman/01/06.jpg'),
                require('./woman/01/07.jpg'),
                require('./woman/01/08.jpg')
            ],
            price: '299',
            residue: 6,
            keys: ['10频震动', '6频伸缩', '3频摇摆', '恒温42℃', '无线遥控'],
            params: [
                { label: '品牌', value: 'COC' },
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '肉色' },
                { label: '材质', value: '液态硅胶' },
                { label: '尺寸', value: '全全长20cm，直径3.8cm，可插入14.5cm' },
                { label: '频率', value: '伸缩款/伸缩摇摆款：6频伸缩/摇摆，10频震动' },
                { label: '充电方式', value: '磁吸USB充电' },
                { label: '充电时长', value: '2小时' },
                { label: '使用时长', value: '1小时' },
                { label: '控制方式', value: '无线遥控' },
                { label: '净重', value: '554g' },
                { label: '主要功能', value: '伸缩/伸缩摇摆/摇摆' },
                { label: '产品特色', value: '无线遥控（10m），液态硅胶' },
                { label: '防水性能', value: '全身防水' },
                { label: '包装清单', value: '阳具*1、遥控器*1、说明书*1' },
            ]
        },
        {
            id: 'woman02',
            name: 'COC 爱丽丝 伸缩震动白色震动棒[货号:QZ21368]',
            images: [
                require('./woman/02/01.jpg'),
                require('./woman/02/02.jpg'),
                require('./woman/02/03.jpg'),
                require('./woman/02/04.jpg'),
                require('./woman/02/05.jpg'),
                require('./woman/02/06.jpg'),
                require('./woman/02/07.jpg'),
                require('./woman/02/08.jpg')
            ],
            price: '159',
            residue: 5,
            keys: ['多频', '伸缩', '阴道刺激', '棒身螺纹', '硅胶材质'],
            params: [
                { label: '品牌', value: 'COC' },
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '白色' },
                { label: '材质', value: '硅胶+ABS' },
                { label: '尺寸', value: '约226*34mm' },
                { label: '频率', value: '10' },
                { label: '充电时长', value: '120min' },
                { label: '使用时长', value: '60min' },
                { label: '净重', value: '290g' },
                { label: '包装清单', value: '震动棒，说明书，收纳袋，数据线' },
            ]
        },
        {
            id: 'woman03',
            name: '爽米 逼真柔软仿真舌部震动摇摆浪舌震动器[货号:QZ25430]',
            images: [
                require('./woman/03/01.jpg'),
                require('./woman/03/02.jpg'),
                require('./woman/03/03.jpg'),
                require('./woman/03/04.jpg'),
                require('./woman/03/05.jpg'),
                require('./woman/03/06.jpg'),
                require('./woman/03/07.jpg'),
                require('./woman/03/08.jpg')
            ],
            price: '179',
            residue: 5,
            keys: ['强震', '摇摆', '多频'],
            params: [
                { label: '品牌', value: '爽米' },
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '酒红色' },
                { label: '材质', value: '硅胶+abs+TPE' },
                { label: '尺寸', value: '196mm×W：46mm×H' },
                { label: '频率', value: '震动/摇摆频率：（10）档' },
                { label: '充电时长', value: '80-120min' },
                { label: '使用时长', value: '0.6h' },
                { label: '净重', value: '155g' },
                { label: '静音性能', value: '距离35cm,实测噪音≤60dB' },
            ]
        },
        {
            id: 'woman04',
            name: 'ZALO 蓝牙互动 尊贵女王震动器[货号:QZ25763]',
            images: [
                require('./woman/04/02.jpg'),
                require('./woman/04/01.jpg'),
                require('./woman/04/03.jpg'),
                require('./woman/04/04.jpg'),
                require('./woman/04/05.jpg'),
                require('./woman/04/06.jpg'),
                require('./woman/04/07.jpg'),
                require('./woman/04/08.jpg')
            ],
            price: '869',
            residue: 2,
            keys: ['8档震动', '8档波动', '加温吮吸', 'APP控制'],
            params: [
                { label: '品牌', value: 'ZALO' },
                { label: '产地', value: '苏州' },
                { label: '颜色', value: '宝石绿，暮光紫' },
                { label: '材质', value: '硅胶，ABS' },
                { label: '尺寸', value: '216x43x55mm' },
                { label: '频率', value: '震动/摇摆频率：（10）档' },
                { label: '充电方式', value: 'USB磁吸式充电' },
                { label: '充电时长', value: '120min' },
                { label: '使用时长', value: '1~2小时' },
                { label: '净重', value: '164g' },
                { label: '静音性能', value: '小于40分贝' },
                { label: '控制方式', value: '单机操作或手机APP控制' },
                { label: '防水性能', value: 'IPx4' },
            ]
        },
        {
            id: 'woman05',
            name: '爱世界 豆豆悦 声波吮吸双头可用 震动器[货号:QZ20962]',
            images: [
                require('./woman/05/01.jpg'),
                require('./woman/05/02.jpg'),
                require('./woman/05/03.jpg'),
                require('./woman/05/04.jpg'),
                require('./woman/05/05.jpg'),
                require('./woman/05/06.jpg'),
                require('./woman/05/07.jpg'),
                require('./woman/05/08.jpg'),
                require('./woman/05/09.jpg'),
                require('./woman/05/10.jpg')
            ],
            price: '198',
            residue: 3,
            keys: ['5频吮吸', '8频震动', '多点刺激', '智能加温'],
            params: [
                { label: '品牌', value: '爱世界' },
                { label: '产地', value: '深圳' },
                { label: '颜色', value: '嫩粉,冰蓝,高贵紫' },
                { label: '材质', value: '硅胶，ABS' },
                { label: '尺寸', value: '158x38x22mm' },
                { label: '充电方式', value: 'USB磁吸式充电' },
                { label: '充电时长', value: '约90分钟' },
                { label: '使用时长', value: '充满电后50分钟以上' },
                { label: '净重', value: '68g' },
                { label: '静音性能', value: '60db以下，20cm' },
                { label: '防水性能', value: '生活防水（可在浴缸使用）' },
            ]
        },
        {
            id: 'woman06',
            name: 'SIYI 植物萃取 温润热感 燃情润滑快感液30ml[货号:QZ0169]',
            images: [
                require('./woman/06/01.jpg'),
                require('./woman/06/02.jpg'),
                require('./woman/06/03.jpg'),
                require('./woman/06/04.jpg'),
                require('./woman/06/05.jpg'),
                require('./woman/06/06.jpg')
            ],
            price: '168',
            residue: 3,
            keys: ['快感增强', '润滑', '保湿', '平衡PH值', '植物萃取'],
            params: [
                { label: '品牌', value: 'SIYI' },
                { label: '产地', value: '中国·广东' },
                { label: '包装清单', value: 'SIYI快感液*1、说明书*1' },
                { label: '容量', value: '30ml' },
                { label: '质地', value: '液体' },
                { label: '规格', value: '单瓶装' },
                { label: '有效期', value: '以收到实物包装日期为主' },
                { label: '使用类型', value: '充涂抹型' },
                { label: '使用方法', value: '挤出适量产品，轻轻地涂抹在阴蒂和私密处，轻柔按摩片刻' },
                { label: '主要成分', value: '透明质酸、丙二醇、薄荷脑、热感剂、丙三醇、纤维素、纯净水等' },
                { label: '质保期', value: '3年' },
            ]
        },
        {
            id: 'woman07',
            name: 'Orgie 葡萄牙进口 小金瓶女性跳动快感增强液15ml[货号:QZ21036]',
            images: [
                require('./woman/07/01.jpg'),
                require('./woman/07/02.jpg'),
                require('./woman/07/03.jpg'),
                require('./woman/07/04.jpg'),
                require('./woman/07/05.jpg'),
                require('./woman/07/06.jpg'),
                require('./woman/07/07.jpg'),
                require('./woman/07/08.jpg'),
                require('./woman/07/09.jpg'),
            ],
            price: '329',
            residue: 5,
            keys: ['酥麻', '跳动', '快速燃情', '原装进口'],
            params: [
                { label: '品牌', value: 'Orgie' },
                { label: '产地', value: '葡萄牙' },
                { label: '颜色', value: '透明液体' },
                { label: '容量', value: '15ml' },
                { label: '适用人群', value: '针对性冷淡不敏感，又有点干涩的女性人群设计' },
                { label: '质地', value: '精油' },
                { label: '有效期', value: '6个月' },
                { label: '产品特色', value: '同时具有凉感、热感和酥麻跳动感，带有香甜的桃子香气' },
                { label: '功能', value: '带来酥麻的快感，让口爱更有快感，渗透性好易吸收，见效快' },
                { label: '使用方法', value: '建议每次使用1、2滴，涂在私密部位，可根据自身需求适量调整用量' },
                { label: '主要成分', value: '甘油，水，香气，金钮扣花精华提取物，乳酸' }
            ]
        },
        {
            id: 'woman08',
            name: 'Angel&coco 外用抑菌凝胶女用快感液30ml[货号:QZ9044]',
            images: [
                require('./woman/08/01.jpg'),
                require('./woman/08/02.jpg'),
                require('./woman/08/03.jpg'),
                require('./woman/08/04.jpg'),
                require('./woman/08/05.jpg'),
                require('./woman/08/06.jpg'),
                require('./woman/08/07.jpg'),
                require('./woman/08/08.jpg'),
            ],
            price: '499',
            residue: 4,
            keys: ['美国进口', '增强活力', '促进血液循环'],
            params: [
                { label: '品牌', value: 'angel&coco' },
                { label: '包装清单', value: '凝露*1' },
                { label: '容量', value: '30ml 可用100次以上' },
                { label: '产地', value: '美国' },
                { label: '质地', value: '凝胶' },
                { label: '有效期', value: '以收到实物包装日期' },
                { label: '使用类型', value: '涂抹型' },
                { label: '产品特色', value: '进口细胞营养液' },
                { label: '使用方法', value: '取适量抹在阴蒂和私密处按摩' },
                { label: '质保期', value: '2年' },
                { label: '主要成分', value: '紫霄花、丁香、肉桂、肉苁蓉、苦参、土茯苓、益母草、红豆杉、醋酸氯己定0.1%、纯化水、益母草纯植物提取液等' }
            ]
        },
        {
            id: 'woman09',
            name: '曼诺 爱莉 螺纹刺激多频震动跳蛋[货号:QZ50034]',
            images: [
                require('./woman/09/01.jpg'),
                require('./woman/09/02.jpg'),
                require('./woman/09/03.jpg'),
                require('./woman/09/04.jpg'),
            ],
            price: '99',
            residue: 4,
            keys: ['多频', '震动', '剐蹭', '单跳'],
            params: [
                { label: '品牌', value: '曼诺 mannuo'},
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '紫色,玫红' },
                { label: '材质', value: 'ABS+硅胶' },
                { label: '尺寸', value: '跳蛋：8.5*3.1 拉绳：5， 遥控：6.8*3.3cm，可插入尺寸(cm) 6.5cm' },
                { label: '频率', value: '10频' },
                { label: '充电方式', value: 'usb' },
                { label: '充电时长', value: 'USB 1.5H' },
                { label: '使用时长', value: '1h' },
                { label: '控制方式', value: '长按跳蛋按键开/关机，短按调节震动频率，共10频。产品开机后可配合遥控使用，点按遥控按键调节震动频率，共10频；长按遥控按键跳蛋暂停震动，再次点按恢复震动' },
                { label: '净重', value: '65g' },
                { label: '主要功能', value: '震动' },
                { label: '防水性能', value: '可配合除菌香皂用清水洗净，清洗时不可打开金属帽盖' },
                { label: '包装清单', value: '跳蛋*1、遥控*1、数据线*1、说明书*1' },
                { label: '注意事项', value: '1、充电时避免接触水源；2、皮肤损伤者禁止使用' },
            ]
        },
        {
            id: 'woman10',
            name: '安芮 智能声控强力震动 电击跳蛋[货号:QZ25404]',
            images: [
                require('./woman/10/01.jpg'),
                require('./woman/10/02.jpg'),
                require('./woman/10/03.jpg'),
                require('./woman/10/04.jpg'),
                require('./woman/10/05.jpg'),
                require('./woman/10/06.jpg'),
                require('./woman/10/07.jpg'),
                require('./woman/10/08.jpg'),
                require('./woman/10/09.jpg'),
            ],
            price: '129',
            residue: 8,
            keys: ['多频', '震动', '10m遥控'],
            params: [
                { label: '品牌', value: '安芮'},
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '黑色' },
                { label: '静音性能', value: '≤60DB' },
                { label: '材质', value: '硅胶+ABS' },
                { label: '尺寸', value: '155*32*34mm' },
                { label: '频率', value: '10频震动/电击、声控' },
                { label: '充电方式', value: 'DC充电口' },
                { label: '控制方式', value: '声控、按键遥控' },
                { label: '净重', value: '70g' },
                { label: '主要功能', value: '震动' },
                { label: '防水性能', value: '跳蛋IPX5，遥控器不防水' },
                { label: '包装清单', value: '跳蛋*1、遥控器*1、说明书*1、数据线*1' },
            ]
        }
    ],
    man: [
        {
            id: 'man01',
            name: 'NO17-久皇外用喷剂（经典款） 15ml[货号:QZ9750]',
            images: [
                require('./man/01/01.jpg'),
                require('./man/01/02.jpg'),
                require('./man/01/03.jpg'),
                require('./man/01/04.jpg'),
                require('./man/01/05.jpg'),
                require('./man/01/06.jpg')
            ],
            price: '198',
            residue: 8,
            keys: ['藏传配方', '温和', '无依赖', '植物萃取', '易吸收', '起效快', '无麻木'],
            params: [
                { label: '品牌', value: 'NO17-久皇'},
                { label: '产地', value: '郑州' },
                { label: '容量', value: '15ml（可使用约70次）' },
                { label: '包装清单', value: '喷剂1支、说明书*1' },
                { label: '质地', value: '液体' },
                { label: '规格', value: '单只装' },
                { label: '有效期', value: '2年（本品效果良好，建议每次喷涂不超过3下）' },
                { label: '使用类型', value: '喷洒型' },
                { label: '产品特色', value: '藏传中医古秘方 高原名贵植物提取' },
                { label: '使用方法', value: '提前30分钟,每次喷2-3下于龟头冠状沟处,吸收完后立即清洗' },
                { label: '主要成分', value: '五倍子 苦参 蛇床子 黄柏 纯化水 醋酸氯已定等' },
                { label: '质保期', value: '以收到实物包装日期为主' }
            ]
        },
        {
            id: 'man02',
            name: '雅迪克 植物提取男用抑菌喷剂10ml[货号:QZ3642]',
            images: [
                require('./man/02/01.jpg'),
                require('./man/02/02.jpg'),
                require('./man/02/03.jpg'),
                require('./man/02/04.jpg'),
                require('./man/02/05.jpg'),
                require('./man/02/06.jpg'),
                require('./man/02/07.jpg'),
                require('./man/02/08.jpg'),
            ],
            price: '198',
            residue: 8,
            keys: ['苗家配方', '科学延时', '妙方精华', '滋养', '天然', '安全配方', '温和易吸收', '无麻木'],
            params: [
                { label: '品牌', value: '雅迪克'},
                { label: '产地', value: '广东省' },
                { label: '容量', value: '10ML' },
                { label: '包装清单', value: '喷剂1支、说明书*1' },
                { label: '质地', value: '液体' },
                { label: '规格', value: '瓶' },
                { label: '有效期', value: '2以收到实物日期为准' },
                { label: '使用类型', value: '喷洒型' },
                { label: '产品特色', value: '滋养龙根 ，中医古秘方，珍稀植物萃取' },
                { label: '使用方法', value: '提前30分钟,每次喷2-3下（新手喷涂1-2下）于龟头冠状沟处,吸收完后立即清洗' },
                { label: '主要成分', value: '牡蛎肽、淫羊藿、玛咖提取液、三氯生、芦荟、丙三醇、纯净水等' },
                { label: '质保期', value: '24个月' }
            ]
        },
        {
            id: 'man03',
            name: 'UJAY 智能加温震动夹吸免提果儿飞机杯[货号:QZ9875]',
            images: [
                require('./man/03/01.jpg'),
                require('./man/03/02.jpg'),
                require('./man/03/03.jpg'),
                require('./man/03/04.jpg'),
                require('./man/03/05.jpg'),
                require('./man/03/06.jpg'),
                require('./man/03/07.jpg'),
                require('./man/03/08.jpg'),
                require('./man/03/09.jpg'),
                require('./man/03/10.jpg'),
            ],
            price: '299',
            residue: 8,
            keys: ['刺激度4星', '互动', '震动', '夹吸', '带吸盘', '6频强震感应', '42°智能恒温'],
            params: [
                { label: '品牌', value: 'U-JAY'},
                { label: '产地', value: '温州' },
                { label: '颜色', value: '时尚黑白色' },
                { label: '控制方式', value: '电动' },
                { label: '类型', value: '阴交' },
                { label: '震动频率', value: '6频强震' },
                { label: '充电方式', value: 'USB充电' },
                { label: '充电时间', value: '2小时' },
                { label: '使用时长', value: '1小时' },
                { label: '主功能', value: '自动夹吸 智能加温' },
                { label: '尺寸', value: '全长29cm（加吸盘），胶体长15cm，直径7.8cm' },
                { label: '净重', value: '575g' },
                { label: '主要材质', value: 'TPE+ABS' },
                { label: '产品特色', value: '智能恒温42°  六频夹震 声音可外放可插耳机' },
                { label: '包装清单', value: '飞机杯*1USB充电线*1润滑油*1保养粉*1免提固定圈*1说明书*1' },
            ]
        },
        {
            id: 'man04',
            name: 'OTOUCH 魅惑口爱锻炼型飞机杯[货号:QZ1887]',
            images: [
                require('./man/04/01.jpg'),
                require('./man/04/02.jpg'),
                require('./man/04/03.jpg'),
                require('./man/04/04.jpg'),
                require('./man/04/05.jpg'),
                require('./man/04/06.jpg'),
                require('./man/04/07.jpg'),
                require('./man/04/08.jpg'),
                require('./man/04/09.jpg'),
                require('./man/04/10.jpg'),
                require('./man/04/11.jpg'),
                require('./man/04/12.jpg'),
            ],
            price: '269',
            residue: 8,
            keys: ['刺激度1星', '深喉', '锻炼降敏', '口交', '持久'],
            params: [
                { label: '品牌', value: 'OTOUCH'},
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '黑红' },
                { label: '震动频率', value: '6种频率，3种强度' },
                { label: '充电方式', value: 'USB充电' },
                { label: '充电时间', value: '1.5小时' },
                { label: '使用时长', value: '60分钟' },
                { label: '主功能', value: '自慰，顶部刺激' },
                { label: '副功能', value: '降低敏感，持久训练' },
                { label: '防水性能', value: '全生活防水' },
                { label: '尺寸', value: '头部直径35mm，插入高度40mm-45mm' },
                { label: '净重', value: '230g' },
                { label: '主要材质', value: '硅胶+ABS' },
            ]
        },
        {
            id: 'man05',
            name: 'COC丽娜 人工植毛智能语音聊天 阴臀倒模[货号:QZ20900]',
            images: [
                require('./man/05/01.jpg'),
                require('./man/05/02.jpg'),
                require('./man/05/03.jpg'),
                require('./man/05/04.jpg'),
                require('./man/05/05.jpg'),
                require('./man/05/06.jpg'),
                require('./man/05/07.jpg'),
                require('./man/05/08.jpg'),
                require('./man/05/09.jpg'),
                require('./man/05/10.jpg'),
                require('./man/05/11.jpg'),
            ],
            price: '399',
            residue: 8,
            keys: ['1:1真人比例', '人工植毛', '互动发音'],
            params: [
                { label: '品牌', value: 'COC'},
                { label: '产地', value: '东莞' },
                { label: '控制方式', value: '手动' },
                { label: '类型', value: '阴交/肛交' },
                { label: '充电方式', value: 'USB充电' },
                { label: '充电时间', value: '1.5小时' },
                { label: '使用时长', value: '60分钟' },
                { label: '主功能', value: '互动发音，感应震动' },
                { label: '防水性能', value: '生活防水（发音器不防水）' },
                { label: '尺寸', value: '6.5*31*19cm，可插入尺寸约8cm' },
                { label: '净重', value: '约4.5kg' },
                { label: '主要材质', value: 'TPE' },
                { label: '注意事项', value: '支持圆孔耳机播放及外放，阴毛为人工植毛，易脱落，请勿拉扯' },
                { label: '包装清单', value: '倒模*1，说明书*1，充电线*1' },
            ]
        },
        {
            id: 'man06',
            name: '卿卿 玉女性感酥胸双交软嫩果冻乳[货号:QZ20477]',
            images: [
                require('./man/06/01.jpg'),
                require('./man/06/02.jpg'),
                require('./man/06/03.jpg'),
                require('./man/06/04.jpg'),
                require('./man/06/05.jpg'),
                require('./man/06/06.jpg'),
                require('./man/06/07.jpg'),
                require('./man/06/08.jpg'),
                require('./man/06/09.jpg'),
                require('./man/06/10.jpg'),
                require('./man/06/11.jpg'),
                require('./man/06/12.jpg'),
                require('./man/06/13.jpg'),
                require('./man/06/14.jpg'),
                require('./man/06/15.jpg'),
                require('./man/06/16.jpg'),
            ],
            price: '269',
            residue: 8,
            keys: ['酥胸', '柔软', '白嫩', '富有弹性'],
            params: [
                { label: '品牌', value: '卿卿'},
                { label: '产地', value: '广东' },
                { label: '颜色', value: '肤色' },
                { label: '主功能', value: '乳交，阴交' },
                { label: '副功能', value: '满足男性对巨乳的幻想，解决自慰需求' },
                { label: '防水性能', value: '生活防水' },
                { label: '尺寸', value: '220*190*135mm，可插入13cm' },
                { label: '净重', value: '约2.3kg' },
                { label: '主要材质', value: 'TPE' },
                { label: '产品特色', value: '巨乳酥胸，乳阴双交' },
                { label: '注意事项', value: '放在通风干燥处保存' },
            ]
        },
        {
            id: 'man07',
            name: 'COC 巨乳榨汁小妹贝卡双通道逼真名器[货号:QZ21001]',
            images: [
                require('./man/07/01.jpg'),
                require('./man/07/02.jpg'),
                require('./man/07/03.jpg'),
                require('./man/07/04.jpg'),
                require('./man/07/05.jpg'),
                require('./man/07/06.jpg'),
                require('./man/07/07.jpg'),
                require('./man/07/08.jpg'),
                require('./man/07/09.jpg'),
                require('./man/07/10.jpg'),
                require('./man/07/11.jpg'),
            ],
            price: '168',
            residue: 8,
            keys: ['丰乳娇臀', '榨汁神器', '逼真双通道', '2.6斤重量级'],
            params: [
                { label: '品牌', value: 'COC'},
                { label: '产地', value: '中国大陆' },
                { label: '颜色', value: '肤色' },
                { label: '控制方式', value: '手动' },
                { label: '类型', value: '阴交/肛交' },
                { label: '主功能', value: '自慰' },
                { label: '副功能', value: '阴、肛双通道体验' },
                { label: '尺寸', value: '25*9.5*14.5cm；可插入尺寸阴部12cm，肛部11cm' },
                { label: '净重', value: '1.3kg' },
                { label: '主要材质', value: 'TPE' },
                { label: '产品特色', value: '果冻酥胸，喷血手感，阴、肛、乳三重体验' },
                { label: '包装清单', value: '名器*1、套套*2、润滑油*2、保护粉*1' },
            ]
        },
        {
            id: 'man08',
            name: 'COC 微笑唇口阴肛三通道榨汁名器[货号:QZ20952]',
            images: [
                require('./man/08/01.jpg'),
                require('./man/08/02.jpg'),
                require('./man/08/03.jpg'),
                require('./man/08/04.jpg'),
                require('./man/08/05.jpg'),
                require('./man/08/06.jpg'),
            ],
            price: '128',
            residue: 8,
            keys: ['蜜唇体验', '紧致肉厚', '逼真', '触感真实', '口阴菊三通道'],
            params: [
                { label: '品牌', value: 'COC'},
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '深肤色' },
                { label: '控制方式', value: '手动' },
                { label: '类型', value: '口交/阴交/肛交' },
                { label: '主功能', value: '手动自慰' },
                { label: '尺寸', value: '2口3.2/阴1.2/肛0.5cm' },
                { label: '净重', value: '550g' },
                { label: '主要材质', value: 'TPE' },
                { label: '产品特色', value: '贯通通道，逼真人脸造型+口腔结构，独特三通道设计，一物多用' },
            ]
        },
        {
            id: 'man09',
            name: 'SVAKOM 二代升级夫妻共震男用双环锁精环[货号:QZ3740]',
            images: [
                require('./man/09/01.jpg'),
                require('./man/09/02.jpg'),
                require('./man/09/03.jpg'),
                require('./man/09/04.jpg'),
                require('./man/09/05.jpg'),
                require('./man/09/06.jpg'),
                require('./man/09/07.jpg'),
                require('./man/09/08.jpg'),
                require('./man/09/09.jpg'),
            ],
            price: '199',
            residue: 8,
            keys: ['双环', '吮吸挑逗', '5频震动', '拉伸性好', '男女共震'],
            params: [
                { label: '品牌', value: 'SVAKOM'},
                { label: '产地', value: '深圳' },
                { label: '颜色', value: '紫色' },
                { label: '震动频率', value: '5种' },
                { label: '充电方式', value: 'USB充电' },
                { label: '充电时间', value: '20.5小时' },
                { label: '使用时长', value: '1小时' },
                { label: '主功能', value: '男女共震、锁精缓射，助勃锻炼' },
                { label: '防水性能', value: '充电口处不防水' },
                { label: '静音性能', value: '低于50分贝' },
                { label: '尺寸', value: '80*42*51.6mm  大圈直径48mm 小圈直径28mm' },
                { label: '净重', value: '31g' },
                { label: '主要材质', value: '硅胶' },
                { label: '产品特色', value: '物理锁精不伤身 舌舔毛刷刺激' },
                { label: '包装清单', value: '震动器*1、说明书*1、USB充电线*1' },
            ]
        },
        {
            id: 'man10',
            name: 'GALAKU 龟头按摩阴茎训练器[货号:QZ20910]',
            images: [
                require('./man/10/01.jpg'),
                require('./man/10/02.jpg'),
                require('./man/10/03.jpg'),
                require('./man/10/04.jpg'),
                require('./man/10/05.jpg'),
                require('./man/10/06.jpg'),
                require('./man/10/07.jpg'),
            ],
            price: '168',
            residue: 8,
            keys: ['源于日本', '阴茎锻炼', '新手推荐', '可视化表盘'],
            params: [
                { label: '品牌', value: 'Galaku'},
                { label: '产地', value: '日本' },
                { label: '颜色', value: '灰色+白色套装' },
                { label: '控制方式', value: '有线遥控' },
                { label: '类型', value: '阴交' },
                { label: '震动频率', value: '8频12速' },
                { label: '充电方式', value: '控制器USB充电' },
                { label: '充电时间', value: '控制器充满2-3小时' },
                { label: '使用时长', value: '1.5-2小时' },
                { label: '主功能', value: '阴茎锻炼' },
                { label: '副功能', value: '自慰按摩' },
                { label: '防水性能', value: '胶体防水，控制器不防水' },
                { label: '静音性能', value: '小于80分贝' },
                { label: '尺寸', value: '软胶：8.7*5.4cm，入口直径2cm，白色款可插入长度8.5cm，有弹性；控制器：9.75*2.3*5.6cm，跳蛋：3.1*1.5cm,  外包装：20.5*15.5*6.5cm；' },
                { label: '净重', value: '330g' },
                { label: '主要材质', value: 'ABS+TPE' },
                { label: '产品特色', value: '可视化表盘，震频、电量清晰可见，便于选择喜好频率' },
                { label: '注意事项', value: '胶体可浸泡，跳蛋可冲洗，控制器不防水' },
                { label: '包装清单', value: '训练器*2 控制器+1对跳蛋*1 说明书*1 数据线*1' },
            ]
        }
    ],
    clothing: [
        {
            id: 'clothing01',
            name: '欧姿丽雅 开裆透明绣花 性感火辣丁字裤[货号:QZ9300]',
            images: [
                require('./clothing/01/01.jpg'),
                require('./clothing/01/02.jpg'),
                require('./clothing/01/03.jpg'),
                require('./clothing/01/04.jpg'),
                require('./clothing/01/05.jpg'),
                require('./clothing/01/06.jpg'),
                require('./clothing/01/07.jpg'),
            ],
            price: '39',
            residue: 8,
            keys: ['丁字裤', '开裆', '绣花', '透视', '蕾丝', '情趣'],
            params: [
                { label: '品牌', value: '欧姿丽雅'},
                { label: '产地', value: '江苏' },
                { label: '适穿对象', value: '腰围（56-72cm)' },
                { label: '主面料', value: '基布：锦纶100%,绣线：聚酯纤维100%' },
                { label: '款式', value: '开档内裤' },
                { label: '商品颜色', value: '红色' },
                { label: '包装清单', value: '丁字裤*1' }
            ]
        },
        {
            id: 'clothing02',
            name: '史黛丝 蕾丝钻石镂空情趣内裤[货号:QZ25568-1]',
            images: [
                require('./clothing/02/01.jpg'),
                require('./clothing/02/02.jpg'),
                require('./clothing/02/03.jpg'),
                require('./clothing/02/04.jpg'),
                require('./clothing/02/05.jpg'),
                require('./clothing/02/06.jpg'),
                require('./clothing/02/07.jpg'),
            ],
            price: '38',
            residue: 8,
            keys: ['精致彩钻', '性感蕾丝', '精致高雅'],
            params: [
                { label: '品牌', value: '史黛丝'},
                { label: '可选颜色', value: '黑色/酒红色/白色' },
                { label: '尺寸', value: '均码' },
                { label: '风格', value: '成熟' },
                { label: '款式', value: '开档内裤' },
                { label: '面料', value: '锦纶+氨纶' },
                { label: '产品特色', value: '精致彩钻' },
                { label: '包装清单', value: '情趣内裤/1条' },
            ]
        },
        {
            id: 'clothing03',
            name: '性感吊带网袜 极致诱惑 高腰网袜[货号:QZ25178-1]',
            images: [
                require('./clothing/03/01.jpg'),
                require('./clothing/03/02.jpg'),
                require('./clothing/03/03.jpg'),
                require('./clothing/03/04.jpg'),
                require('./clothing/03/05.jpg'),
                require('./clothing/03/06.jpg'),
            ],
            price: '39',
            residue: 8,
            keys: ['网袜.吊袜带', '高腰', '情趣'],
            params: [
                { label: '品牌', value: '史黛丝'},
                { label: '产地', value: '东莞' },
                { label: '可选颜色', value: '黑色' },
                { label: '风格', value: '火辣' },
                { label: '产品特色', value: '蕾丝花纹网袜' },
                { label: '包装清单', value: '吊带网袜*1' },
            ]
        },
        {
            id: 'clothing04',
            name: '霏慕 超薄闪光一线成熟性感透视开档连裤袜[货号:QZ21150]',
            images: [
                require('./clothing/04/01.jpg'),
                require('./clothing/04/02.jpg'),
                require('./clothing/04/03.jpg'),
                require('./clothing/04/04.jpg'),
                require('./clothing/04/05.jpg'),
            ],
            price: '28',
            residue: 8,
            keys: ['闪光', '开裆', '性感', '透明'],
            params: [
                { label: '品牌', value: '霏慕'},
                { label: '产地', value: '义乌' },
                { label: '可选颜色', value: '黑/肤/灰' },
                { label: '风格', value: '成熟' },
                { label: '产品特色', value: '闪光，引人视线' },
                { label: '包装清单', value: '单件连裤袜' },
            ]
        },
        {
            id: 'clothing05',
            name: '霏慕 15D含硅胶 油亮蕾丝花边长筒袜[货号:QZ1657]',
            images: [
                require('./clothing/05/01.jpg'),
                require('./clothing/05/02.jpg'),
                require('./clothing/05/03.jpg'),
                require('./clothing/05/04.jpg'),
                require('./clothing/05/05.jpg'),
                require('./clothing/05/06.jpg'),
            ],
            price: '39',
            residue: 8,
            keys: ['黑丝', '防滑', '蕾丝', '花边', '性感', '诱惑'],
            params: [
                { label: '品牌', value: '霏慕'},
                { label: '产地', value: '义乌' },
                { label: '尺码', value: '身高：155cm-180cm；体重：40kg-65kg' },
                { label: '风格', value: '性感' },
                { label: '材质', value: '蕾丝' },
                { label: '包装清单', value: '长筒袜一双（不含内裤、吊袜带）' },
            ]
        },
        {
            id: 'clothing06',
            name: '三点式聚拢蕾丝诱惑火辣情趣内衣套装[货号:QZ25174]',
            images: [
                require('./clothing/06/01.jpg'),
                require('./clothing/06/02.jpg'),
                require('./clothing/06/03.jpg'),
                require('./clothing/06/04.jpg'),
                require('./clothing/06/05.jpg'),
            ],
            price: '99',
            residue: 8,
            keys: ['蕾丝', '镂空', '性感', '套装', '精致'],
            params: [
                { label: '品牌', value: '史黛丝'},
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '红色、黑色、白色' },
                { label: '风格', value: '火辣' },
                { label: '面料', value: '蕾丝' },
                { label: '包装清单', value: '文胸*1，内裤*1，吊袜带*1（不包含丝袜）' },
            ]
        },
        {
            id: 'clothing07',
            name: '史黛丝 白色蕾丝透视网纱性感睡裙套装[货号:QZ25933-1]',
            images: [
                require('./clothing/07/01.jpg'),
                require('./clothing/07/02.jpg'),
                require('./clothing/07/03.jpg'),
                require('./clothing/07/04.jpg'),
                require('./clothing/07/05.jpg'),
            ],
            price: '99',
            residue: 8,
            keys: ['性感', '纯欲', '蕾丝', '网纱', '透视诱惑', '高级套装'],
            params: [
                { label: '品牌', value: '史黛丝'},
                { label: '产地', value: '东莞' },
                { label: '颜色', value: '红白色' },
                { label: '风格', value: '火辣' },
                { label: '面料', value: '蕾丝' },
                { label: '尺码', value: '均码' },
                { label: '产品特色', value: '透视网纱，轻薄透气，外穿内搭。高级感套装' },
            ]
        },
        {
            id: 'clothing08',
            name: '清纯猫女游戏制服诱惑套装[货号:Q1677-1]',
            images: [
                require('./clothing/08/01.jpg'),
                require('./clothing/08/02.jpg'),
                require('./clothing/08/03.jpg'),
                require('./clothing/08/04.jpg'),
                require('./clothing/08/05.jpg'),
                require('./clothing/08/06.jpg'),
                require('./clothing/08/07.jpg'),
            ],
            price: '66',
            residue: 8,
            keys: ['性感情趣内衣', '连体开裆式制服'],
            params: [
                { label: '品牌', value: '瑰若'},
                { label: '产地', value: '东莞' },
                { label: '角色扮演', value: '其他' },
                { label: '主面料', value: '冰丝' },
                { label: '适穿对象', value: '成年女性' },
                { label: '款式', value: '性感开裆' },
                { label: '包装清单', value: '发箍、手环*2、连体套装' },
            ]
        },
        {
            id: 'clothing09',
            name: '史黛丝 性感紧身包臀秘书OL教师套装[货号:QZ25853-1]',
            images: [
                require('./clothing/09/01.jpg'),
                require('./clothing/09/02.jpg'),
                require('./clothing/09/03.jpg'),
                require('./clothing/09/04.jpg'),
                require('./clothing/09/05.jpg'),
            ],
            price: '89',
            residue: 8,
            keys: ['教师', 'cosplay', '空姐', '秘书', 'OL', '包臀', '性感', '性感教师'],
            params: [
                { label: '品牌', value: '史黛丝'},
                { label: '主面料', value: '上衣：100%聚酯纤维，裙：85.8%聚酯纤维，14.2%氨纶，领结：100%聚酯纤维' },
                { label: '适穿对象', value: '80-125斤' },
                { label: '腰围', value: '34cm' },
                { label: '胸围', value: '47cm' },
                { label: '包装清单', value: '领结+上衣+短裙+T裤' }
            ]
        },
        {
            id: 'clothing10',
            name: 'JK制服蕾丝格纹聚拢诱惑情趣内衣套装[货号:QZ21965]',
            images: [
                require('./clothing/10/01.jpg'),
                require('./clothing/10/02.jpg'),
                require('./clothing/10/03.jpg'),
                require('./clothing/10/04.jpg'),
                require('./clothing/10/05.jpg'),
                require('./clothing/10/06.jpg'),
                require('./clothing/10/07.jpg'),
                require('./clothing/10/08.jpg'),
                require('./clothing/10/09.jpg'),
                require('./clothing/10/10.jpg'),
            ],
            price: '88',
            residue: 8,
            keys: ['Jk制服', '日系', '性感', '套装'],
            params: [
                { label: '品牌', value: '史黛丝'},
                { label: '产地', value: '东莞'},
                { label: '主面料', value: '95%聚酯纤维、5%氨纶' },
                { label: '角色扮演', value: '学生' },
                { label: '款式', value: '性感露乳' },
                { label: '商品颜色', value: '紫色' }
            ]
        }
    ],
    condom: [
        {
            id: 'condom01',
            name: '杰士邦持久系列避孕套[货号:QZ25224]',
            images: [
                require('./condom/01/01.jpg'),
                require('./condom/01/02.jpg'),
                require('./condom/01/03.jpg'),
                require('./condom/01/04.jpg'),
                require('./condom/01/05.jpg'),
                require('./condom/01/06.jpg'),
                require('./condom/01/07.jpg'),
                require('./condom/01/08.jpg'),
            ],
            price: '109',
            residue: 8,
            keys: ['薄润贴合', '延时持久', '局部降敏', '挤压不侧漏'],
            params: [
                { label: '品牌', value: '杰士邦'},
                { label: '产地', value: '印度'},
                { label: '型号', value: '标称宽度53mm' },
                { label: '主功能', value: '延时持久' },
                { label: '副功能', value: '超薄 ，挤压不侧漏' },
                { label: '产品特色', value: '享受延时的同时还可紧密贴合' },
                { label: '材质', value: '橡胶' },
                { label: '套械(X)字号', value: '国械注进20173666944' },
                { label: '注意事项', value: '避免放到阳光直射的地方，本品为一次性使用产品' },
            ]
        },
        {
            id: 'condom02',
            name: '冈本 003系列薄避孕套系列[货号:QZ9624]',
            images: [
                require('./condom/02/01.jpg'),
                require('./condom/02/02.jpg'),
                require('./condom/02/03.jpg'),
                require('./condom/02/04.jpg'),
                require('./condom/02/05.jpg'),
                require('./condom/02/06.jpg'),
                require('./condom/02/07.jpg'),
                require('./condom/02/08.jpg'),
            ],
            price: '139',
            residue: 8,
            keys: ['日本进口', '0.03mm', '防过敏', '不易破', '超薄体感 享受性福'],
            params: [
                { label: '品牌', value: '冈本'},
                { label: '产地', value: '日本'},
                { label: '规格', value: '10只装' },
                { label: '型号', value: '直径33mm' },
                { label: '产品特色', value: '超薄贴身  及时体验 薄如蝉翼,激情无阻' },
                { label: '材质', value: '乳胶' },
                { label: '套械(X)字号', value: '国械注进20162662257' },
                { label: '包装清单', value: '避孕套*1盒' },
                { label: '保质期', value: '5年' },
            ]
        },
        {
            id: 'condom03',
            name: '杜蕾斯 001系列 聚氨酯避孕套[货号:QZ25197-2]',
            images: [
                require('./condom/03/01.jpg'),
                require('./condom/03/02.jpg'),
                require('./condom/03/03.jpg'),
                require('./condom/03/04.jpg'),
                require('./condom/03/05.jpg'),
                require('./condom/03/06.jpg'),
                require('./condom/03/07.jpg'),
                require('./condom/03/08.jpg'),
            ],
            price: '129.9',
            residue: 8,
            keys: ['日本进口', '0.03mm', '防过敏', '不易破', '超薄体感 享受性福'],
            params: [
                { label: '品牌', value: '杜蕾斯'},
                { label: '主功能', value: '避孕套'},
                { label: '材质', value: '水性聚氨酯' },
                { label: '尺寸', value: '54mm' },
                { label: '套械(X)字号', value: '甘械注准20212180104' },
            ]
        },
        {
            id: 'condom04',
            name: 'OLO 印度伽摩古秘方避孕套 10只装[货号:QZ3663-1]',
            images: [
                require('./condom/04/01.jpg'),
                require('./condom/04/02.jpg'),
                require('./condom/04/03.jpg'),
                require('./condom/04/04.jpg'),
                require('./condom/04/05.jpg'),
            ],
            price: '59',
            residue: 8,
            keys: ['龟龙精设计', '锁精延时', '激战到底', '玻尿酸元素', '添加由多种植物精炼的奔腾因子'],
            params: [
                { label: '品牌', value: 'OLO'},
                { label: '产地', value: '中国'},
                { label: '主功能', value: '避孕' },
                { label: '产品特色', value: '超薄 玻尿酸水溶' },
                { label: '材质', value: '天然乳胶' },
                { label: '套械(X)字号', value: '甘械注准20172660002' },
                { label: '质保期', value: '5年' },
                { label: '尺寸', value: '见彩盒背面' },
            ]
        },
        {
            id: 'condom05',
            name: '杜蕾斯 活力装避孕套 中号 3/12只装[货号:Q9615]',
            images: [
                require('./condom/05/01.jpg'),
                require('./condom/05/02.jpg'),
                require('./condom/05/03.jpg'),
                require('./condom/05/04.jpg'),
                require('./condom/05/05.jpg'),
            ],
            price: '49.9',
            residue: 8,
            keys: ['清新香草味', '让爱爱 活力四射'],
            params: [
                { label: '品牌', value: '杜蕾斯'},
                { label: '产地', value: '青岛'},
                { label: '主功能', value: '避孕' },
                { label: '产品特色', value: '超薄体贴' },
                { label: '材质', value: '天然乳胶' },
                { label: '套械(X)字号', value: '鲁械注准20162180063' },
                { label: '质保期', value: '5年' },
                { label: '尺寸', value: '直径33mm' },
            ]
        },
        {
            id: 'condom06',
            name: '狼牙套大颗粒避孕套10只装[货号:QZ20743-1]',
            images: [
                require('./condom/06/01.jpg'),
                require('./condom/06/02.jpg'),
                require('./condom/06/03.jpg'),
                require('./condom/06/04.jpg'),
                require('./condom/06/05.jpg'),
                require('./condom/06/06.jpg'),
            ],
            price: '29.9',
            residue: 8,
            keys: ['超大颗粒', '加倍润滑', '柔软乳胶', '大颗粒刺激狼牙套', '颗颗激情，粒粒激爽，含超润滑硅油润滑剂'],
            params: [
                { label: '品牌', value: 'ELASUN尚牌'},
                { label: '产地', value: '湖南'},
                { label: '主功能', value: '避孕' },
                { label: '产品特色', value: '大颗粒刺激狼牙套，颗颗激情' },
                { label: '材质', value: '天然乳胶' },
                { label: '套械(X)字号', value: '湘械注准20182660002' },
                { label: '质保期', value: '5年' },
                { label: '尺寸', value: '52±2mm' },
            ]
        }
    ],
    sm: [
        {
            id: 'sm01',
            name: '美加奴 sm入门初级调教四件套[货号:Q2670-1]',
            images: [
                require('./sm/01/01.jpg'),
                require('./sm/01/02.jpg'),
                require('./sm/01/03.jpg'),
                require('./sm/01/04.jpg'),
                require('./sm/01/05.jpg'),
                require('./sm/01/06.jpg'),
                require('./sm/01/07.jpg'),
            ],
            price: '78',
            residue: 8,
            keys: ['虐恋', '蕾丝', '鞭打', '视觉剥夺', 'SM情趣'],
            params: [
                { label: '品牌', value: '美加奴'},
                { label: '产地', value: '深圳'},
                { label: '颜色', value: '黑色&红色' },
                { label: '尺寸', value: '眼罩7.8*20cm，手铐25.5*6cm，皮鞭46.5cm，肛塞7.5*3cm' },
                { label: '材料', value: '蕾丝、PVC、硅胶、皮革、潜水绵、边纶布、尼龙织带' },
                { label: '重量', value: '约305g' },
                { label: '适用人群', value: '成年人' },
                { label: '特色', value: '蕾丝诱惑，皮革鞭打，硅胶肛塞' },
                { label: '包装清单', value: '套装*1盒' },
            ]
        },
        {
            id: 'sm02',
            name: '云曼 SM调教 黑色简约口球[货号:QZ21102]',
            images: [
                require('./sm/02/01.jpg'),
                require('./sm/02/02.jpg'),
                require('./sm/02/03.jpg'),
                require('./sm/02/04.jpg'),
                require('./sm/02/05.jpg'),
                require('./sm/02/06.jpg'),
                require('./sm/02/07.jpg'),
                require('./sm/02/08.jpg'),
            ],
            price: '148',
            residue: 8,
            keys: ['口球', '口塞', '羞辱', '情趣', 'SM用品'],
            params: [
                { label: '品牌', value: '云曼'},
                { label: '产地', value: '东莞'},
                { label: '颜色', value: '黑色' },
                { label: '尺寸', value: '入口直径4.4cm，佩带范围35-52cm' },
                { label: '材料', value: '蕾丝、PVC、硅胶、皮革、潜水绵、边纶布、尼龙织带' },
                { label: '重量', value: '103g' },
                { label: '适用人群', value: '成年人' },
                { label: '主要材质', value: '硅胶' },
                { label: '包装清单', value: '口水球*1' },
            ]
        },
        {
            id: 'sm03',
            name: '嘉冠 SM情趣 羽毛手拍[货号:QZ21202-2]',
            images: [
                require('./sm/03/01.jpg'),
                require('./sm/03/02.jpg'),
                require('./sm/03/03.jpg'),
                require('./sm/03/04.jpg'),
            ],
            price: '69',
            residue: 8,
            keys: ['sm', 'spank', '手拍', '调情', '羽毛拍'],
            params: [
                { label: '品牌', value: '嘉冠'},
                { label: '产地', value: '佛山'},
                { label: '颜色', value: '黑色' },
                { label: '尺寸', value: '49*6.2cm' },
                { label: '重量', value: '17.6g' },
                { label: '主功能', value: 'SM调教 羽毛撩拨调情' },
                { label: '主要材质', value: 'PU、羽毛' },
                { label: '包装清单', value: '拍子*1' },
                { label: '注意事项', value: '羽毛不建议清洗，皮革拍建议湿纸巾擦拭' },
            ]
        },
        {
            id: 'sm04',
            name: '润裕 SM调情 铁链束乳带[货号:QZ21295]',
            images: [
                require('./sm/04/01.jpg'),
                require('./sm/04/02.jpg'),
                require('./sm/04/03.jpg'),
                require('./sm/04/04.jpg'),
                require('./sm/04/05.jpg'),
                require('./sm/04/06.jpg'),
                require('./sm/04/07.jpg'),
                require('./sm/04/08.jpg'),
                require('./sm/04/09.jpg'),
                require('./sm/04/10.jpg'),
            ],
            price: '88',
            residue: 8,
            keys: ['sm', '束乳', '调情', '铁链'],
            params: [
                { label: '品牌', value: '润裕'},
                { label: '产地', value: '佛山'},
                { label: '颜色', value: '黑色' },
                { label: '尺寸', value: '90.2*51.6*31.6cm' },
                { label: '重量', value: '160g' },
                { label: '主功能', value: '调情束缚' },
                { label: '主要材质', value: 'pu、铁' },
                { label: '包装清单', value: '束乳带*1' },
            ]
        },
        {
            id: 'sm05',
            name: '美加奴 SM荔枝纹情趣散鞭[货号:Q2673-1]',
            images: [
                require('./sm/05/01.jpg'),
                require('./sm/05/02.jpg'),
                require('./sm/05/03.jpg'),
                require('./sm/05/04.jpg'),
                require('./sm/05/05.jpg'),
            ],
            price: '58',
            residue: 8,
            keys: ['散鞭', '鞭打', '调教', '惩罚', '羞辱', '情趣'],
            params: [
                { label: '品牌', value: '美加奴'},
                { label: '产地', value: '深圳'},
                { label: '颜色', value: '黑色' },
                { label: '尺寸', value: '全长75.5cm，手柄长18.5cm' },
                { label: '重量', value: '约175g' },
                { label: '控制方式', value: '手动' },
                { label: '主要材质', value: '荔枝纹皮革' },
                { label: '适用人群', value: '成年男女' },
                { label: '特色', value: 'SM调教' },
                { label: '包装清单', value: '皮鞭*1' },
            ]
        },
        {
            id: 'sm06',
            name: '夏奇 低温调情 SM滴蜡蜡烛[货号:QZ21387-2]',
            images: [
                require('./sm/06/01.jpg'),
                require('./sm/06/02.jpg'),
                require('./sm/06/03.jpg'),
                require('./sm/06/04.jpg'),
                require('./sm/06/05.jpg'),
            ],
            price: '79',
            residue: 8,
            keys: ['滴蜡', '调教', '45°-48°', '低温蜡烛'],
            params: [
                { label: '品牌', value: '夏奇'},
                { label: '产地', value: '深圳'},
                { label: '颜色', value: '黑色' },
                { label: '尺寸', value: '6.1*5*4.1cm' },
                { label: '重量', value: '60g' },
                { label: '主要材质', value: '椰子蜡、大豆蜡、香精、精油' },
                { label: '主功能', value: 'SM滴蜡调情' },
                { label: '副功能', value: '照明、香薰、按摩' },
                { label: '特色', value: '滋润肌肤，45°-48°低温' },
                { label: '包装清单', value: '蜡烛*1' },
                { label: '包装清单', value: '1.每次点燃前将烛芯修剪至5-8毫米，便于充分燃烧 2.如需滴蜡，待蜡烛融化成精油状后将蜡烛熄灭，再按需使用1.使用时请远离易燃物品，避免火灾 2.请放置在儿童和宠物无法触及的地方 3.本品为天然低温植物椰子蜡，有滋养功效，建议单次使用不超过两小时' },
            ]
        }
    ],
    nurse: [
        {
            id: 'nurse01',
            name: '雅迪克 黄金羊胎素夫妻专业润滑液 私处润滑女性易洗型润滑油 2瓶*200ml[货号:QZ20454]',
            images: [
                require('./nurse/01/01.jpg'),
                require('./nurse/01/02.jpg'),
                require('./nurse/01/03.jpg'),
                require('./nurse/01/04.jpg'),
                require('./nurse/01/05.jpg'),
                require('./nurse/01/06.jpg'),
                require('./nurse/01/07.jpg'),
            ],
            price: '99',
            residue: 8,
            keys: ['胎素紧致精华', '进口原液', '不油腻易清洗', '私处滋养', '易冲免洗持久30分钟润滑', '伴侣'],
            params: [
                { label: '品牌', value: '雅迪克'},
                { label: '产地', value: '国产'},
                { label: '容量', value: '400ml' },
                { label: '质地', value: '液体' },
                { label: '规格', value: '2*200ml' },
                { label: '有效期', value: '见外包装' },
                { label: '使用类型', value: '涂抹型' },
                { label: '主功能', value: '持久润滑 滋养紧致阴道' },
                { label: '产品特色', value: '马来西亚羊胎素 超大容量  持久润滑' },
                { label: '主要成分', value: '去离子水、EDTANa2、尼泊金甲酯、羟乙基纤维素、甘油、羊胎素精华，透明质酸。' },
                { label: '是否清洗', value: '本产品易吸收。若感不适，请即使清洗' },
                { label: '使用时间', value: '持久湿润30分钟左右' },
                { label: '使用方法', value: '1、旋开瓶盖；2、把尖嘴对准私处/飞机杯口等玩具，用力挤压；3、用手涂抹均匀于私处或玩具身上；4、用完后旋紧瓶盖' },
                { label: '注意事项', value: '1、不建议做唇吸润滑液使用；2、孕期时，请按照自身情况，谨遵医嘱后使用；3、不要阳光直射；4、使用完毕后旋紧瓶盖' },
            ]
        },
        {
            id: 'nurse02',
            name: '久兴 热感缓痛后庭润滑液 95ml[货号:QZ20265]',
            images: [
                require('./nurse/02/01.jpg'),
                require('./nurse/02/02.jpg'),
                require('./nurse/02/03.jpg'),
                require('./nurse/02/04.jpg'),
                require('./nurse/02/05.jpg'),
                require('./nurse/02/06.jpg'),
            ],
            price: '108',
            residue: 8,
            keys: ['后庭专用', '尖嘴盖设计', '缓痛热感', '保湿配方', '充分润滑不干涩'],
            params: [
                { label: '品牌', value: 'JEUSN 久兴'},
                { label: '产地', value: '广东东莞'},
                { label: '容量', value: '95ml' },
                { label: '质地', value: '液体' },
                { label: '规格', value: '瓶' },
                { label: '有效期', value: '见外包装' },
                { label: '使用类型', value: '涂抹型，尖嘴插入' },
                { label: '主功能', value: '润滑 缓痛热感' },
                { label: '产品特色', value: '润滑、缓痛，尖嘴插入更方便' },
                { label: '主要成分', value: '是' },
                { label: '是否清洗', value: '本产品易吸收。若感不适，请即使清洗' },
                { label: '使用时间', value: '持久湿润30分钟左右' },
                { label: '使用方法', value: '使用灌肠器械清洗肛门后，再尖嘴插入，挤入。' },
                { label: '注意事项', value: '阴茎，肛门，破皮，炎症，过敏勿使用，注意用使用分量，越抽插越热，由于过热，引起红肿，灼伤肛门，阴茎' },
            ]
        },
        {
            id: 'nurse03',
            name: '羞羞哒 玻尿酸 滋润保湿水基润滑液[货号:QZ20864]',
            images: [
                require('./nurse/03/01.jpg'),
                require('./nurse/03/02.jpg'),
                require('./nurse/03/03.jpg'),
                require('./nurse/03/04.jpg'),
                require('./nurse/03/05.jpg'),
                require('./nurse/03/06.jpg'),
                require('./nurse/03/07.jpg'),
                require('./nurse/03/08.jpg'),
            ],
            price: '128',
            residue: 8,
            keys: ['富含玻尿酸', '私处补水', '润滑保湿', '易清洗', '清爽不黏', '免水洗', '近人体体液'],
            params: [
                { label: '品牌', value: '羞羞哒'},
                { label: '产地', value: '广东东莞'},
                { label: '质地', value: '透明液体' },
                { label: '规格', value: '300g/瓶' },
                { label: '有效期', value: '3年' },
                { label: '使用类型', value: '涂抹型' },
                { label: '主功能', value: '私处润滑保湿，易清洗' },
                { label: '产品特色', value: '润滑、缓痛，尖嘴插入更方便' },
                { label: '主要成分', value: '玻尿酸、纯净水、丙三醇、蛋清素、丙二醇、纤维素' },
                { label: '是否清洗', value: '清水冲洗即可' },
                { label: '使用时间', value: '约20-30分钟' },
                { label: '使用方法', value: '取适量涂抹于私处即可' },
            ]
        },
        {
            id: 'nurse04',
            name: 'MOVO迷恋型紧致/粉嫩款精华液[货号:QZ21031]',
            images: [
                require('./nurse/04/01.jpg'),
                require('./nurse/04/02.jpg'),
                require('./nurse/04/03.jpg'),
                require('./nurse/04/04.jpg'),
            ],
            price: '188',
            residue: 8,
            keys: ['紧致私处', '水润养护', '焕发新生'],
            params: [
                { label: '品牌', value: 'MOVO'},
                { label: '产地', value: '广州'},
                { label: '质地', value: '凝胶' },
                { label: '规格', value: '30ML' },
                { label: '有效期', value: '3年' },
                { label: '主功能', value: '粉嫩/紧致' },
                { label: '产品特色', value: '植物精华萃取，安全放心' },
                { label: '主要成分', value: '粉嫩款：水，甘油，丙二醇，葡萄柚（CITRUSPARADISI）提取物，卡波姆，三乙醇胺，菊粉，a-葡聚糖寡糖，醋酸氯已定。紧致款：水，甘油，丙二醇，葡萄柚（CITRUSPARADISI）提取物，二棕榈酰羟脯氨酸，卡波姆，三乙醇胺，冰片，醋酸氯已定' },
                { label: '使用时间', value: '开封后60天内用完' },
                { label: '使用方法', value: '洁净手后，按压压泵取适量于手指指腹处，将凝胶用手指涂抹阴道内壁，根据自身情况调节用量' },
            ]
        },
        {
            id: 'nurse05',
            name: '安太医 绵柔卫生湿巾 5片装[货号:QZ22001]',
            images: [
                require('./nurse/05/01.jpg'),
                require('./nurse/05/02.jpg'),
                require('./nurse/05/03.jpg'),
                require('./nurse/05/04.jpg'),
                require('./nurse/05/05.jpg'),
            ],
            price: '78',
            residue: 8,
            keys: ['抑菌', '清洁除菌', '滋养防护', '植物萃取'],
            params: [
                { label: '品牌', value: '安太医'},
                { label: '产地', value: '青岛'},
                { label: '材质', value: '绵' },
                { label: '尺寸', value: '8*6.5cm' },
                { label: '有效期', value: '2年' },
                { label: '包装清单', value: '湿巾*5' },
                { label: '注意事项', value: '1、本品仅供外用，避免接触眼睛，不可口服；、皮肤严重过敏者，有伤口和感染者慎用，置于儿童不易触及处；3、如使用后肌肤出现不适，请停止使用；4、请置于阴凉干燥处保存' },
            ]
        },
        {
            id: 'nurse06',
            name: 'Intimate Earth 蒂美缩紧私处润滑啫喱30ml[货号:QZ1761]',
            images: [
                require('./nurse/06/01.jpg'),
                require('./nurse/06/02.jpg'),
                require('./nurse/06/03.jpg'),
                require('./nurse/06/04.jpg'),
            ],
            price: '78',
            residue: 8,
            keys: ['进口', '提欲', '缩阴', '润滑', '美国原装进口，植物萃取'],
            params: [
                { label: '品牌', value: 'Intimate Earth蒂美'},
                { label: '产地', value: '美国'},
                { label: '材质', value: '啫喱' },
                { label: '容量', value: '30ML' },
                { label: '主要成分', value: '水、丙二醇、乳酸锰酯、辣椒素、枸杞浆果提取物、柠檬香茅提取物、芦荟提取物等' },
                { label: '特色', value: '收缩女性私处，激发情欲，滋养水润' },
                { label: '类型', value: '涂抹型' },
                { label: '用法', value: '涂抹' },
                { label: '包装清单', value: '缩紧啫喱*1瓶' },
            ]
        }
    ]
}


export const getList = (name) => {
    return product[name]
}

export const getDetail = (id) => {
    let result = null
    for (let key of Object.keys(product)) {
        for(let item of product[key]) {
            if(item.id == id) result = item 
        }
    }
    return result
}